language: c

matrix:
  include:
    - os: osx
      osx_image: xcode11.4
    - os: osx
      osx_image: xcode11.3
    - os: linux

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install Caskroom/cask/osxfuse; fi

script:
  - ./INSTALL
