language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
    - os: linux

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install Caskroom/cask/osxfuse; fi

script:
  - ./INSTALL
